openapi: 3.0.0
info:
  version: 0.0.1
  title: Flux API
  contact:
    email: tadeas@zel.network
    url: 'https://docs.fluxapi.runonflux.io'
  license:
    name: GNU AGPLv3
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'
  x-logo:
    url: 'https://raw.githubusercontent.com/runonflux/fluxdocs/master/flux.jpg'
  description: |-
    This is an API documentation of calls available to be made to Flux API. <br> GET Calls are available as both query and in order as path. <br> Flux API is completely open source and we encourage everyone to feel free and contribute :) <br> Further questions or support join and ask in our [discord](https://discord.io/runonflux)

    # Introduction
    Flux API is a collection of API's being used to collect all data needed by Flux Stats Dashboard 
    # Getting Started with the API
    1. You can use browser directly to access the API's


    2. You can also use any client tools such as postman or soap ui to access the API's
externalDocs:
  description: Flux API
  url: 'https://github.com/runonflux/fluxapi'
tags:
  - name: Flux Info
    description: Request that are neccessary for collecting node data
  - name: Flux History
    description: Request that are neccessary for collecting ip history
  - name: Flux Versions
    description: Request that are neccessary for collecting flux version
  - name: Flux Locations
    description: Request that are neccessary for collecting node locations
  - name: Flux Locations Now
    description: Request that are neccessary for collecting node locations
  - name: Flux History Stats
    description: Request that are neccessary for collecting total node per tier at a specific round time
  - name: Stored Locations
    description: Request that are neccessary for collecting node locations
  - name: Available Times
    description: Request that are neccessary for collecting round time
servers:
  - url: 'https://stats.runonflux.io/'
paths:
  /fluxinfo:
    get:
      parameters:
        - in: query
          name: projection
          schema:
            type: string
            enum:
              - ip
              - addedHeight
              - lastPaidHeight
              - tier
              - activeSince
              - confirmedHeight
              - lastConfirmedHeight
              - collateralHash
              - collateralIndex
              - paymentAddress
              - roundTime
              - dataCollectedAt
              - geolocation
              - daemon
              - node
              - benchmark
              - flux
              - apps
              - appsHashesTotal
              - hashesPresent
              - scannedHeight
              - connectionsOut
              - connectionsIn
              - ''
            example: 'ip,tier'
          required: false
          description: Set of data that can be retrieved
      tags:
        - Flux Info
      summary: All flux node information
      description: Collect node data based on different projections
      operationId: fluxinfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Data set based on projections
                    items:
                      type: object
              example:
                status: success
                data:
                  - daemon:
                      info:
                        version: 6000050
                        protocolversion: 170018
                        walletversion: 60000
                        blocks: 1116065
                        timeoffset: 0
                        connections: 16
                        proxy: ''
                        difficulty: 27419.45286019697
                        testnet: false
                        keypoololdest: 1651265356
                        keypoolsize: 101
                        paytxfee: 0
                        relayfee: 0.000001
                        errors: ''
                    node:
                      status:
                        status: CONFIRMED
                        collateral: 'COutPoint(08194c8cfb97d7c4613ae47b89ddf81935e08028b2f7a380f14021cd13c7ca50, 0)'
                        txhash: 08194c8cfb97d7c4613ae47b89ddf81935e08028b2f7a380f14021cd13c7ca50
                        outidx: '0'
                        ip: '65.108.120.181:16157'
                        network: ''
                        added_height: 1079394
                        confirmed_height: 1079397
                        last_confirmed_height: 1115972
                        last_paid_height: 1108713
                        tier: CUMULUS
                        payment_address: t1e7c7cXNx4aDcXcWLY17ZvkQVxUpSrj4in
                        pubkey: 04f8e1d1a6049392089a64e8fcf606f1f8496eff322541eb0e7bbce466aa20ad983c0ee5e568d56ff2d09334b3541db0e2e36182ce033d668040365b535224ca9e
                        activesince: '1647543614'
                        lastpaid: '1651087768'
                        amount: '1000.00'
                    benchmark:
                      info:
                        version: 3.2.0
                        rpcport: 16224
                      status:
                        status: online
                        benchmarking: CUMULUS
                        flux: connected
                      bench:
                        ipaddress: '65.108.120.181:16157'
                        architecture: amd64
                        armboard: ''
                        status: CUMULUS
                        time: 1651973985
                        real_cores: 2
                        cores: 4
                        ram: 7.8
                        ssd: 230
                        hdd: 0
                        ddwrite: 299.51
                        totalstorage: 230
                        disksinfo:
                          - disk: sda
                            size: 230
                            writespeed: 299.51
                        eps: 1793.16
                        ping: 4.824999809265137
                        download_speed: 905.1500244140625
                        upload_speed: 872.3099975585938
                        bench_version: 1.0.20
                        speed_version: 2.1.2
                        error: ''
                    flux:
                      version: 3.16.0
                      ip: '65.108.120.181:16157'
                      zelid: 1HHLQmbdMXooDL9PkXUoN1MtK1iM8Jbzqr
                      cruxid: null
                      timezone: UTC
                      dos:
                        dosState: 0
                        dosMessage: null
                    apps:
                      fluxusage: '0.27500000'
                      runningapps:
                        - Id: 0a501829d4577a17131ae0417ca17e96b276c26341ae53b654b10c42b7d6dbb7
                          Names:
                            - /flux_watchtower
                          Image: containrrr/watchtower
                          ImageID: 'sha256:333de6ea525af9137e1f14a5c1bfaa2e730adca97ab97f74d738dfa99967f14f'
                          Command: /watchtower --cleanup --interval 10890
                          Created: 1651266197
                          Ports:
                            - PrivatePort: 8080
                              Type: tcp
                          Labels:
                            com.centurylinklabs.watchtower: 'true'
                          State: running
                          Status: Up 8 days
                      resources:
                        appsCpusLocked: 0
                        appsRamLocked: 0
                        appsHddLocked: 0
                    geolocation:
                      ip: 65.108.120.181
                      continent: null
                      continentCode: null
                      country: Finland
                      countryCode: FI
                      region: '18'
                      regionName: Uusimaa
                      lat: 60.1719
                      lon: 24.9347
                      org: Hetzner Online GmbH
                    ip: '65.108.120.181:16157'
                    addedHeight: 1079394
                    confirmedHeight: 1079397
                    lastConfirmedHeight: 1115972
                    lastPaidHeight: 1108713
                    tier: CUMULUS
                    paymentAddress: t1e7c7cXNx4aDcXcWLY17ZvkQVxUpSrj4in
                    activeSince: '1647543614'
                    collateralHash: 08194c8cfb97d7c4613ae47b89ddf81935e08028b2f7a380f14021cd13c7ca50
                    collateralIndex: 0
                    roundTime: 1651975613157
                    appsHashesTotal: 2964
                    hashesPresent: 2931
                    scannedHeight: 1116065
                    connectionsOut:
                      - 94.130.70.88
                      - 176.9.19.157
                      - 142.132.250.168
                      - 96.51.21.132
                      - 65.43.222.98
                      - 76.176.51.110
                      - 65.108.79.59
                      - 38.88.125.27
                      - 89.58.40.213
                      - 192.99.34.149
                      - 162.55.85.204
                      - 65.108.199.173
                      - 202.61.197.168
                      - 81.7.13.152
                      - 185.216.176.168
                      - 138.201.190.171
                      - 45.142.177.32
                      - 65.108.97.26
                      - 188.2.191.120
                      - 46.38.232.201
                      - 95.216.33.227
                      - 65.108.120.238
                      - 95.216.124.211
                      - 31.7.195.245
                      - 5.39.11.88
                      - 5.161.85.244
                      - 46.38.233.51
                      - 45.129.180.70
                      - 65.108.96.163
                      - 65.108.99.220
                      - 65.21.168.147
                      - 135.181.201.223
                      - 72.210.11.158
                      - 108.230.253.35
                      - 142.132.250.246
                      - 51.254.51.112
                      - 123.172.51.77
                      - 5.161.93.22
                      - 91.244.197.227
                      - 85.219.222.227
                      - 185.30.117.12
                      - 198.27.68.184
                      - 88.119.251.55
                      - 168.220.198.30
                      - 185.216.177.54
                      - 195.206.229.82
                      - 138.75.41.233
                      - 65.108.105.28
                      - 82.66.157.171
                      - 5.161.79.205
                    connectionsIn:
                      - 5.161.85.36
                      - 65.21.207.40
                      - 89.58.40.225
                      - 164.92.155.158
                      - 88.99.20.4
                      - 65.108.12.229
                      - 135.181.255.25
                      - 202.61.204.166
                      - 135.181.151.180
                      - 185.136.186.247
                      - 144.126.139.214
                      - 65.108.131.80
                      - 202.61.247.226
                      - 198.27.103.201
                      - 89.58.33.177
                      - 146.255.194.244
                      - 65.108.131.80
                      - 194.61.28.27
                      - 65.108.96.155
                      - 51.77.76.127
                      - 181.214.147.84
                      - 76.239.131.28
                      - 161.97.162.210
                      - 37.221.192.234
                      - 202.61.243.190
                      - 92.151.55.144
                      - 87.104.24.152
                      - 167.114.174.224
                      - 144.126.149.37
                      - 65.108.218.66
                      - 95.216.214.19
                      - 89.58.32.242
                      - 65.108.62.62
                      - 65.108.79.24
                      - 185.30.117.175
                      - 74.105.84.127
                      - 65.108.120.68
                      - 65.108.143.158
                      - 95.214.55.240
                      - 5.161.79.25
                      - 65.108.104.28
                      - 146.255.194.242
                      - 94.23.204.164
                      - 92.151.55.144
                      - 51.222.122.173
                      - 94.16.111.37
                      - 88.119.251.34
                      - 185.150.18.13
                      - 65.108.132.95
                      - 89.58.42.83
                      - 192.95.8.72
                      - 5.161.87.118
                      - 65.108.218.52
                      - 95.217.219.133
                      - 66.94.101.100
                      - 135.181.57.52
                    dataCollectedAt: 1651975618358
  /fluxhistory/ip:
    get:
      parameters:
        - in: query
          name: ip
          schema:
            type: string
            example: 192.168.0.1
          required: true
          description: Flux node IP for retriving it's history
      tags:
        - Flux History
      summary: Flux node history using IP
      description: Collect node history
      operationId: fluxhistory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Data set based on ip
                    items:
                      type: object
              example:
                status: success
                data:
                  - daemon:
                      info:
                        version: 6000050
                        protocolversion: 170018
                        walletversion: 60000
                        blocks: 1102467
                        timeoffset: 0
                        connections: 16
                        proxy: ''
                        difficulty: 25130.53435221701
                        testnet: false
                        keypoololdest: 1650282920
                        keypoolsize: 101
                        paytxfee: 0
                        relayfee: 0.000001
                        errors: ''
                    node:
                      status:
                        status: CONFIRMED
                        collateral: 'COutPoint(43c12f4e50a4d3751318246bc7595749b3c44163e5295801a63031b6b8213b98, 0)'
                        txhash: 43c12f4e50a4d3751318246bc7595749b3c44163e5295801a63031b6b8213b98
                        outidx: '0'
                        ip: 94.130.70.88
                        network: ipv4
                        added_height: 1102077
                        confirmed_height: 1102080
                        last_confirmed_height: 1102451
                        last_paid_height: 0
                        tier: CUMULUS
                        payment_address: t1YeRhuE75a6SWvcBwxZDkamrs4TAUvzExB
                        pubkey: 045daac4aae91481e731510ea28ed5dc1d6ed9712085fc45ff6aca9e782c5d12cd2eb9600c5060fc9a6b196eb7a0011e704991bec2e02dcdeed0c70ee5fe7643fe
                        activesince: '1650284293'
                        lastpaid: '1516980000'
                        amount: '1000.00'
                    benchmark:
                      info:
                        version: 3.2.0
                        rpcport: 16224
                      status:
                        status: online
                        benchmarking: CUMULUS
                        flux: connected
                      bench:
                        ipaddress: 94.130.70.88
                        architecture: amd64
                        armboard: ''
                        status: CUMULUS
                        time: 1650332419
                        real_cores: 4
                        cores: 4
                        ram: 7.8
                        ssd: 220
                        hdd: 0
                        ddwrite: 1591
                        totalstorage: 220
                        disksinfo:
                          - disk: sda
                            size: 220
                            writespeed: 1591
                        eps: 1824.6
                        ping: 3.413000106811523
                        download_speed: 934.52001953125
                        upload_speed: 920.25
                        bench_version: 1.0.20
                        speed_version: 2.1.2
                        error: ''
                    flux:
                      version: 3.15.0
                      ip: 94.130.70.88
                      zelid: 1Pe2X7Brnz43pLs5Nh3Jh9xuCqkmnR8EnK
                      cruxid: null
                      timezone: UTC
                      dos:
                        dosState: 0
                        dosMessage: null
                    apps:
                      fluxusage: '0.23500000'
                      runningapps:
                        - Id: 83b9f4cd560e51adfcaeab809d745c47856e7f463d206051d3372b241ab16390
                          Names:
                            - /flux_watchtower
                          Image: containrrr/watchtower
                          ImageID: 'sha256:333de6ea525af9137e1f14a5c1bfaa2e730adca97ab97f74d738dfa99967f14f'
                          Command: /watchtower --cleanup --interval 20453
                          Created: 1650283285
                          Ports:
                            - PrivatePort: 8080
                              Type: tcp
                          Labels:
                            com.centurylinklabs.watchtower: 'true'
                          State: running
                          Status: Up 14 hours
                      resources:
                        appsCpusLocked: 0
                        appsRamLocked: 0
                        appsHddLocked: 0
                    geolocation:
                      ip: 94.130.70.88
                      continent: null
                      continentCode: null
                      country: Germany
                      countryCode: DE
                      region: SN
                      regionName: Saxony
                      lat: 50.475
                      lon: 12.365
                      org: Hetzner
                    ip: 94.130.70.88
                    addedHeight: 1102077
                    confirmedHeight: 1102080
                    lastConfirmedHeight: 1102329
                    lastPaidHeight: 0
                    tier: CUMULUS
                    paymentAddress: t1YeRhuE75a6SWvcBwxZDkamrs4TAUvzExB
                    activeSince: '1650284293'
                    collateralHash: 43c12f4e50a4d3751318246bc7595749b3c44163e5295801a63031b6b8213b98
                    collateralIndex: 0
                    roundTime: 1650329355560
                    dataCollectedAt: 1650332927533
  /fluxversions:
    get:
      tags:
        - Flux Versions
      summary: All flux node version data
      description: Collect all flux node versions
      operationId: fluxversions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Flux Version Node Information
                    items:
                      type: object
              example:
                status: success
                data:
                  - ip: 45.91.132.241
                    daemon: 6000050
                    benchmark: 3.2.0
                    flux: 3.16.0
                  - ip: 89.58.7.28
                    daemon: 6000050
                    benchmark: 3.2.0
                    flux: 3.16.0
  /fluxlocations:
    get:
      tags:
        - Flux Locations
      summary: All flux node location data
      description: Collect all data about flux node location
      operationId: fluxlocations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Geolocation Node Information
                    items:
                      type: object
              example:
                status: success
                data:
                  - geolocation:
                      ip: 65.108.142.240
                      continent: null
                      continentCode: null
                      country: Finland
                      countryCode: FI
                      region: '18'
                      regionName: Uusimaa
                      lat: 60.1719
                      lon: 24.9347
                      org: Hetzner Online GmbH
                  - geolocation:
                      ip: 65.108.151.25
                      continent: null
                      continentCode: null
                      country: Finland
                      countryCode: FI
                      region: '18'
                      regionName: Uusimaa
                      lat: 60.1719
                      lon: 24.9347
                      org: Hetzner Online GmbH
  /fluxlocationsnow:
    get:
      tags:
        - Flux Locations Now
      summary: All flux node location data
      description: Collect all data about flux node location
      operationId: fluxlocationsnow
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Geolocation Node Information
                    items:
                      type: object
              example:
                status: success
                data:
                  - ip: 1.40.239.80
                    continent: Oceania
                    continentCode: OC
                    country: Australia
                    countryCode: AU
                    region: NSW
                    regionName: New South Wales
                    lat: -33.8715
                    lon: 151.2006
                    org: Optus Internet Pty Ltd
                    _id: 62678bf2d84e62ea130fd2db
                  - ip: 1.40.239.80
                    continent: Oceania
                    continentCode: OC
                    country: Australia
                    countryCode: AU
                    region: NSW
                    regionName: New South Wales
                    lat: -33.8715
                    lon: 151.2006
                    org: Optus Internet Pty Ltd
                    _id: 62690d45b348863465c72570
  /fluxhistorystats:
    get:
      tags:
        - Flux History Stats
      summary: Total flux node per tier
      description: Collect all total nodes per tier at a specific round time
      operationId: fluxhistorystats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: object
                    description: Total nodes per tier at a specific round time
              example:
                status: success
                data:
                  '1650945381809':
                    cumulus: 7743
                    nimbus: 1792
                    stratus: 1526
                  '1651045052336':
                    cumulus: 7794
                    nimbus: 1814
                    stratus: 1534
  /storedlocations:
    get:
      tags:
        - Stored Locations
      summary: All flux node stored location data
      description: Collect all stored location dataa
      operationId: storedlocations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Stored Location Information
                    items:
                      type: object
              example:
                status: success
                data:
                  - ip: 1.40.239.80
                    continent: Oceania
                    continentCode: OC
                    country: Australia
                    countryCode: AU
                    region: NSW
                    regionName: New South Wales
                    lat: -33.8715
                    lon: 151.2006
                    org: Optus Internet Pty Ltd
                  - ip: 1.40.239.80
                    continent: Oceania
                    continentCode: OC
                    country: Australia
                    countryCode: AU
                    region: NSW
                    regionName: New South Wales
                    lat: -33.8715
                    lon: 151.2006
                    org: Optus Internet Pty Ltd
  /availabletimes:
    get:
      tags:
        - Available Times
      summary: All flux round time data
      description: Collect all roundtime data
      operationId: availabletimes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  data:
                    type: array
                    description: Round Time Information
                    items:
                      type: number
              example:
                status: success
                data:
                  - 1650945381809
                  - 1651045052336
components:
  schemas:
    status:
      type: string
      description: Explanation of status
      enum:
        - success
        - error
